### ISSUE TITLE
Does this library truly depend on "ircmaxell/password-compat"

### ISSUE THREAD

**Issue by meadsteve** [vanqard/passman#1]
Just a thought but anyone on a later version of php wouldn't actually need this library in the composer.json.

Maybe it would be better to remove this as a dependency and just check the required function exists in the constructor? People running older versions of php can always add ircmaxell's package themselves in their composer.json.

**Comment by vanqard** [comment]
Hi Steve!

Thank you for your raising this. It's a good point. I thought about that too though. 

What I came up with was considering the situation where two environments aren't in sync - ie. developer has PHP5.5+ locally but hosts with MegaCheapoHostingCorp (with < 5.5). Or in a team environment where developer A has it, developer B doesn't, live maybe does or doesn't. 

I know in an ideal world, all environments would match but... 

My conclusion was that since 'requiring' the password_compat library has a null effect on environments that have the password_\* funcs natively, the 'least surprise' would be achieved just by requiring it anyway. 

Yes? No?

**Comment by meadsteve** [comment]
I think I agree with all the reasons you've got for making the decision. My personal preference would be in making the developers make this choice by adding it to their composer.json so that they can run in many environments. But as said this is a preference rather than something I think you've done wrong.

One thing I would do though to minimise any suprises for devs consuming this is to require a real version of the lib rather than a wildcard one. Maybe something like:

``` json
"ircmaxell/password-compat": "^1.0.4"
```

**Comment by vanqard** [comment]
Yes, you're right about the version requirement - I'll make that change.
